project:
  type: website

website:
  title: "datamodelling_learning_platform_2024"
  output-dir: docs  # This is important for GitHub Pages
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

