project:
  type: website
  output-dir: docs


website:
  title: "My Learning Platform"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: aboutme.qmd
        text: About me
      - href: datamodelling.qmd
        text: Data
      - href: persdevel.qmd
        text: Personal development
      - href: otherinterests.qmd
        text: Other interests

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual



