project:
  type: website  # Specifies the project type
  output-dir: docs  # Output directory for GitHub Pages

# Title and metadata for the website
title: "datamodelling_learning_platform_2024"  # Title of the website
description: "A platform for learning data modeling"  # Optional: description of your website

# Author and date can be included here
author: "Jane Doe"  # Author's name
date: "2024-01-01"  # Date in YYYY-MM-DD format

# Define the chapters of your website
chapters:
  - index.qmd
  - intro.qmd
  - summary.qmd
  - references.qmd

#bibliography: references.bib  # Your bibliography file



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

