name: Quarto Publish

on:
  push:
    branches:
      - main  # Change to your default branch if it's different

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          node-version: '20'


      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y libxml2-dev libxslt-dev

      - name: Install R
        run: |
          sudo apt-get install -y r-base

      - name: Install R Packages
        run: |
          Rscript -e "install.packages(c('knitr', 'rmarkdown', 'quarto'), repos='http://cran.rstudio.com/')"

      - name: Render the site
        run: |
          Rscript -e "quarto::quarto_render()"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
